# general settings
name:  train_HI_Diff_GoPro_PIDCD_S2
model_type: HI_Diff_S2
scale: 1
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: PairedImageIRDataset
    dataroot_gt: datasets/GoPro/crop/train/target_crops
    dataroot_lq: datasets/GoPro/crop/train/input_crops
    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [16,10,8,4,2,2]             # Batch size per gpu   
    iters: [20000,20000,20000,20000,20000,200000]
    gt_size: 384   # Max patch size for progressive training
    gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: PairedImageIRDataset
    dataroot_gt: datasets/GoPro/crop/val/target_crops
    dataroot_lq: datasets/GoPro/crop/val/input_crops
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: PIDCD
  width: 32
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
  bias: False
  LayerNorm_type: WithBias
  embed_dim: 64

network_le:
  type: latent_encoder_gelu
  in_chans: 6
  embed_dim: 64 # same as above
  block_num: 6
  group: 4 # same as above
  stage: 1
  patch_expansion: 0.5
  channel_expansion: 4

network_le_dm:
  type: latent_encoder_gelu
  in_chans: 3
  embed_dim: 64 # same as above
  block_num: 6
  group: 4 # same as above
  stage: 2
  patch_expansion: 0.5
  channel_expansion: 4

network_d:
  type: denoising
  in_channel: 256 # (embed_dim*4)
  out_channel: 256 # (embed_dim*4)
  inner_channel: 512
  block_num: 4
  group: 4 # same as above
  patch_expansion: 0.5
  channel_expansion: 2

diffusion_schedule:
  apply_ldm: False
  schedule: linear
  timesteps: 8
  linear_start: 0.1 # 1e-6
  linear_end: 0.99 # 1e-2

# path
path:
  pretrain_network_g: experiments/debug_train_HI_Diff_GoPro_S1/models/net_g_300000.pth
  param_key_g: params
  strict_load_g: true

  pretrain_network_le: experiments/debug_train_HI_Diff_GoPro_S1/models/net_le_300000.pth
  param_key_g: params
  strict_load_le: true

  pretrain_network_le_dm: ~
  param_key_g: params
  strict_load_le_dm: true

  pretrain_network_d: ~
  param_key_g: params
  strict_load_d: true

  resume_state: ~

# training settings
train:
  total_iter: 300000
  warmup_iter: -1 # no warm up
  use_grad_clip: True

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [100000, 200000]       
    restart_weights: [1,1]
    eta_mins: [0.0002,0.000001]
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_total:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  pixel_diff_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 4e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
